# Generated by Django 5.1.1 on 2024-11-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='subject_choice',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
